### ISSUE TITLE
Delete the Refine module

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#11]
Some of the menu items in the Refine module likely should be made into checkboxes.
Some of the items likely are duplicates of options found on the right pane.

**Comment by pemsley** [comment]
The `Refine` Module should be deleted and its switches added to the `refinement_and_regularization_parameters_dialog` (which is displayed by pressing the "R/RC" button).

**Comment by hgonomeg** [comment]
I think this issue has already been tackled at some point.
