### ISSUE TITLE
The Python window should behave canonically - ie should be a transient of the main window and should be able to be reopened successfully

### ISSUE THREAD

**Issue by pemsley** [hgonomeg/coot#12]
Maybe you can use the exported coot_gui_api.application() to find the window and make the Python window be a transient of that.
That will help not losing the python window. Rank 9.

**Comment by hgonomeg** [comment]
To be read:

https://valadoc.org/gtk+-3.0/Gtk.Window.set_transient_for.html

https://docs.gtk.org/gtk3/property.Window.transient-for.html

**Comment by hgonomeg** [comment]
Merged

**Comment by pemsley** [comment]
While the Python window is now a transient, there is still work to be done with it:
Activating the menu item gives me this:
![Screenshot from 2022-10-01 07-43-21](https://user-images.githubusercontent.com/13886714/193396659-5d88b9e1-770c-42dc-b1cb-ceaef03a37bc.png)
If I close the python script window and reopen it, i get this:

![Screenshot from 2022-10-01 07-44-04](https://user-images.githubusercontent.com/13886714/193396728-b39d706f-967a-410a-abc7-cc17e43ec235.png)

- the entry has disappeared.

And the window can no longer be closed using the WM decoration.

Pressing Escape doesn't close/hide the Python scripting window - it should.

**Comment by hgonomeg** [comment]
Now Esc key also closes the Python scripting window + key-press handling was reworked and improved.
Also "Py" button was added, the layout was improved a bit.
Closing.
