### ISSUE TITLE
The Python scripting window should not be a window

### ISSUE THREAD

**Issue by pemsley** [hgonomeg/coot#13]
The python window should open a new frame or box in the main application - not be a separate dialog. I have in mind something like how Blender handles its scripting (except there is no need for a script editor) - or VS Code. It should be hidden and revealed with a (optionally user-defined) keyboard shortcut. 

This is pretty tricky and "nice to have." Rank 5.

**Comment by hgonomeg** [comment]
Todo: Determine the widget to be used for this

**Comment by hgonomeg** [comment]
# Tasks

* [ ] Determine the widget used for this
* [ ] Do it
* [ ] Test it

**Comment by hgonomeg** [comment]
`Gtk.Revealer` looks good

**Comment by hgonomeg** [comment]
Everything is in place except for the shortcut settings. I think that the shortcut can be done separately though.
I think I can close this issue.
