### ISSUE TITLE
Re-enable Gtk.Overlay in R/RC button

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#16]
Currently the Gtk.Overlay is disabled. Re-enable it and port to GTK4.

# Tasks
* [x] Re-enable Overlay
* ~~Maybe convert checkboxes to Switches?~~ This is something to do under other existent issues such as #11, #10, #17 where appropriate
* [x] Rework how the R/RC dialog is shown altogether

**Comment by pemsley** [comment]
I think we should distinguish between "settings" and display options. The former have no immediate visual effect and should use checkbuttons, the latter change what is being displayed or how the atoms move (i.e. you can see an immediate effect of switching the switch). That mean that the current checkbuttons and radio buttons should stay as checkbuttons.

**Comment by hgonomeg** [comment]
> I think we should distinguish between "settings" and display options. The former have no immediate visual effect and should use checkbuttons, the latter change what is being displayed or how the atoms move (i.e. you can see an immediate effect of switching the switch). That mean that the current checkbuttons and radio buttons should stay as checkbuttons. Did you get a gmail email from me?

Noted down.

**Comment by hgonomeg** [comment]
Merged
